"use client";

import { useEffect, useMemo, useState } from "react";
import type { CatalogTest } from "@/lib/mock-test-types";
import type { ImportQuestion } from "@/lib/question-import";

const questionHeaders = ["question", "option_a", "option_b", "option_c", "option_d", "correct_answer", "subject", "mock_test", "explanation"];
type Preview = { rows: ImportQuestion[]; errors: string[]; detected: number; validRowCount: number; failedRowCount: number; existing: number };
const template = `${questionHeaders.join(",")}\nSample question,Option A,Option B,Option C,Option D,A,General Knowledge,Junior Assistant Mock 01,Optional explanation\n`;

export function AdminQuestionImport() {
  const [tests, setTests] = useState<CatalogTest[]>([]); const [testId, setTestId] = useState(""); const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<Preview | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const selectedTest = useMemo(() => tests.find((test) => test.id === testId), [tests, testId]);

  useEffect(() => { fetch("/api/admin/tests", { cache: "no-store" }).then(async (response) => ({ response, body: await response.json().catch(() => ({})) })).then(({ response, body }) => { if (!response.ok) throw new Error(body.error || "Unable to load mock tests."); setTests(body.data || []); }).catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Unable to load mock tests.")); }, []);
  const downloadTemplate = () => { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([template], { type: "text/csv;charset=utf-8" })); link.download = "jk-test-point-questions-template.csv"; link.click(); URL.revokeObjectURL(link.href); };
  const request = async (path: "/api/admin/questions/preview" | "/api/admin/questions/import") => { if (!testId || !file) { setMessage("Select a target mock test and a CSV/XLSX file first."); return; } setLoading(true); setMessage(""); const form = new FormData(); form.set("testId", testId); form.set("file", file); try { const response = await fetch(path, { method: "POST", body: form }); const body = await response.json().catch(() => ({})); if (path.endsWith("preview")) setPreview(body.data || null); if (!response.ok) throw new Error(body.error || "Import request failed."); setMessage(path.endsWith("import") ? `Imported ${body.data?.imported ?? 0} questions successfully.` : "Preview is ready. Review it before importing."); } catch (error) { setMessage(error instanceof Error ? error.message : "Import request failed."); } finally { setLoading(false); } };
  const readyToImport = !!preview && preview.errors.length === 0 && preview.existing === 0;
  return <section className="container-page py-10"><div className="max-w-6xl"><h1 className="text-3xl font-bold">Admin Question Import</h1><p className="mt-2 text-stone-500">Select a mock test, validate a CSV/XLSX file, then confirm the secure import.</p><div className="card mt-6 space-y-5"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Target mock test<select className="input mt-1" value={testId} onChange={(event) => { setTestId(event.target.value); setPreview(null); }}><option value="">Select a test</option>{tests.map((test) => <option key={test.id} value={test.id}>{test.title}</option>)}</select></label><label className="text-sm font-medium">Question file<input className="input mt-1" type="file" accept=".csv,.xlsx" onChange={(event) => { setFile(event.target.files?.[0] || null); setPreview(null); }} /></label></div>{selectedTest && <p className="rounded-lg bg-stone-50 p-3 text-sm">Selected: <b>{selectedTest.title}</b> · Current: <b>{selectedTest.question_count} questions</b> · Duration: <b>{selectedTest.duration_minutes} minutes</b></p>}<div className="flex flex-wrap gap-3"><button className="btn-secondary" type="button" onClick={downloadTemplate}>Download CSV template</button><button className="btn-primary" type="button" disabled={loading} onClick={() => request("/api/admin/questions/preview")}>{loading ? "Validating…" : "Validate & preview"}</button>{preview && <button className="btn-primary" type="button" disabled={!readyToImport || loading} onClick={() => request("/api/admin/questions/import")}>Confirm import</button>}</div><p className="text-xs text-stone-500">CSV headers: {questionHeaders.join(", ")}. The target test is always assigned server-side.</p>{message && <p className="text-sm font-medium">{message}</p>}{preview && <><p className="text-sm">Detected: <b>{preview.detected}</b> · Valid: <b>{preview.validRowCount}</b> · Failed: <b>{preview.failedRowCount}</b> · Existing: <b>{preview.existing}</b></p>{preview.errors.length > 0 && <ul className="list-disc space-y-1 rounded-lg bg-rose-50 p-4 pl-8 text-sm text-rose-800">{preview.errors.map((error, index) => <li key={`${error}-${index}`}>{error}</li>)}</ul>}<div className="overflow-x-auto rounded-lg border"><table className="min-w-full text-left text-sm"><thead className="bg-stone-50"><tr><th className="p-3">#</th><th className="p-3">Question</th><th className="p-3">A</th><th className="p-3">B</th><th className="p-3">C</th><th className="p-3">D</th><th className="p-3">Answer</th></tr></thead><tbody>{preview.rows.map((row) => <tr className="border-t" key={row.question_number}><td className="p-3">{row.question_number}</td><td className="p-3">{row.question_text}</td><td className="p-3">{row.option_a}</td><td className="p-3">{row.option_b}</td><td className="p-3">{row.option_c}</td><td className="p-3">{row.option_d}</td><td className="p-3">{row.correct_option}</td></tr>)}</tbody></table></div></>}</div></div></section>;
}
