"use client";

import { useState } from "react";
import { MCQ_PRACTICE_SUBJECTS } from "@/lib/mcq-practice";
import type { ImportQuestion } from "@/lib/question-import";

type Preview = { rows: ImportQuestion[]; errors: string[]; detected: number; validRowCount: number; failedRowCount: number; existing: number; canImport: boolean };
const headers = ["question", "option_a", "option_b", "option_c", "option_d", "correct_answer", "subject", "mock_test", "explanation"];

export function AdminSubjectMcqImport() {
  const [subject, setSubject] = useState(""); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<Preview | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const request = async (path: "preview" | "import") => { if (!subject || !file) { setMessage("Select a subject and question file first."); return; } if (path === "preview") setPreview(null); if (path === "import" && !preview?.canImport) { setMessage("Validate the current file successfully before importing."); return; } setLoading(true); setMessage(""); const form = new FormData(); form.set("subject", subject); form.set("file", file); try { const response = await fetch(`/api/admin/subject-mcqs/${path}`, { method: "POST", body: form }); const body = await response.json().catch(() => ({})); if (!response.ok) { if (path === "import" && Array.isArray(body.errors)) setMessage(body.errors.join(" ")); throw new Error(body.error || "Request failed."); } if (path === "preview") setPreview(body.data || null); setMessage(path === "import" ? `Imported ${body.data?.imported ?? 0} ${subject} questions.` : "Preview is ready. Review it before importing."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Request failed."); } finally { setLoading(false); } };
  return <section className="container-page py-10"><div className="max-w-6xl"><p className="eyebrow">Administrator</p><h1 className="mt-2 text-3xl font-bold">Subject MCQ Import</h1><p className="mt-2 text-stone-500">Import real subject-wise MCQs securely. The selected subject is assigned server-side.</p><div className="card mt-6 space-y-5"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Subject<select className="input mt-1" value={subject} onChange={(event) => { setSubject(event.target.value); setPreview(null); }}><option value="">Select a subject</option>{MCQ_PRACTICE_SUBJECTS.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Question file<input className="input mt-1" type="file" accept=".csv,.xlsx" onChange={(event) => { setFile(event.target.files?.[0] || null); setPreview(null); }} /></label></div><div className="flex flex-wrap gap-3"><button className="btn-primary" disabled={loading} type="button" onClick={() => request("preview")}>{loading ? "Validating…" : "Validate & preview"}</button>{preview && <button className="btn-primary" disabled={loading || !preview.canImport} type="button" onClick={() => request("import")}>Confirm import</button>}</div><p className="text-xs text-stone-500">CSV/XLSX headers: {headers.join(", ")}</p>{message && <p className="text-sm font-medium">{message}</p>}{preview && <><p className="text-sm">Detected: <b>{preview.detected}</b> · Valid: <b>{preview.validRowCount}</b> · Failed: <b>{preview.failedRowCount}</b> · Existing: <b>{preview.existing}</b></p>{preview.errors.length > 0 && <ul className="list-disc space-y-1 rounded-lg bg-rose-50 p-4 pl-8 text-sm text-rose-800">{preview.errors.map((error, index) => <li key={`${error}-${index}`}>{error}</li>)}</ul>}</>}</div></div></section>;
}
