"use client";

import { useEffect, useState } from "react";

type Review = { question_id: string; question_number: number; question_text: string; selected_answer?: string | null; correct_answer: string; status: "correct" | "incorrect" | "unattempted"; explanation?: string | null };
type Result = { score: number; percentage: number; total_questions: number; correct: number; incorrect: number; unattempted: number; review: Review[] };

export function SubjectPracticeResult({ subject, attempt }: { subject: string; attempt: string }) {
  const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/mcq-practice/${encodeURIComponent(subject)}/attempt?attempt=${encodeURIComponent(attempt)}`, { cache: "no-store" }).then(async (response) => { const body = await response.json().catch(() => ({})) as { data?: Result; error?: string }; if (!response.ok || !body.data) throw new Error(body.error || "Practice result not found."); return body.data; }).then(setResult).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load practice result.")); }, [attempt, subject]);
  if (error) return <section className="container-page py-10"><div className="card text-center text-rose-700">{error}</div></section>;
  if (!result) return <section className="container-page py-10"><div className="card text-center text-stone-500">Loading practice result…</div></section>;
  return <section className="container-page py-10"><div className="mx-auto max-w-4xl"><div className="page-intro"><p className="eyebrow">Subject practice result</p><h1 className="mt-2 text-3xl font-bold capitalize">{subject}</h1><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-5">{[["Score", result.score], ["Correct", result.correct], ["Incorrect", result.incorrect], ["Unattempted", result.unattempted], ["Accuracy", `${result.percentage}%`]].map(([label, value]) => <div className="meta-tile" key={String(label)}><p className="text-xs font-medium uppercase tracking-wide text-stone-500">{label}</p><b className="mt-2 block text-lg text-stone-800">{value}</b></div>)}</div></div><div className="mt-7 space-y-4">{result.review.map((item) => <article className="card" key={item.question_id}><p className="text-xs font-bold text-brand-600">QUESTION {item.question_number}</p><h2 className="mt-2 font-bold">{item.question_text}</h2><p className={`mt-3 text-sm font-semibold ${item.status === "correct" ? "text-emerald-700" : item.status === "incorrect" ? "text-rose-700" : "text-stone-600"}`}>{item.status === "correct" ? "Correct" : item.status === "incorrect" ? "Incorrect" : "Unattempted"}</p><p className="mt-2 text-sm text-stone-600">Your answer: <b>{item.selected_answer || "Not answered"}</b></p><p className="mt-1 text-sm text-stone-600">Correct answer: <b>{item.correct_answer}</b></p><p className="mt-3 rounded-lg bg-brand-50 p-3 text-sm text-stone-700">{item.explanation || "Explanation not available"}</p></article>)}</div></div></section>;
}
