import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions | JK Test Point",
  description: "Review JK Test Point account, free and paid practice, payment, refund and service-availability terms.",
  alternates: { canonical: "/terms" },
  openGraph: { title: "Terms & Conditions | JK Test Point", description: "Review JK Test Point account, free and paid practice, payment, refund and service-availability terms.", url: "/terms", type: "website" },
  twitter: { card: "summary", title: "Terms & Conditions | JK Test Point", description: "Review JK Test Point account, free and paid practice, payment, refund and service-availability terms." },
};

export default function Terms(){return <section className="container-page py-14"><article className="card mx-auto max-w-3xl"><p className="eyebrow">JK Test Point</p><h1 className="mt-2 text-3xl font-bold">Terms &amp; Conditions</h1><p className="mt-4 leading-7 text-stone-600">JK Test Point provides exam-preparation practice content for educational purposes. By using the site, you agree to use your account and the service responsibly.</p><div className="mt-8 space-y-7 text-stone-600"><section><h2 className="text-xl font-bold text-stone-800">Accounts and acceptable use</h2><p className="mt-2 leading-7">Account access is personal and must not be shared, resold or used to access another student&apos;s data. Do not scrape, copy, disrupt or misuse the question banks, results or site.</p></section><section><h2 className="text-xl font-bold text-stone-800">Free and paid practice</h2><p className="mt-2 leading-7">Free MCQ practice is available without payment. Paid subject MCQs and mock tests are provided only after server-side verification of a successful payment and remain tied to the purchasing account. Content availability may vary by subject or test.</p></section><section><h2 className="text-xl font-bold text-stone-800">Payments and refunds</h2><p className="mt-2 leading-7">Payments are handled through the configured Razorpay flow. Failed or cancelled payments do not grant access. For a payment or refund question, contact support through the Contact page with your order details so the request can be reviewed.</p></section><section><h2 className="text-xl font-bold text-stone-800">Availability</h2><p className="mt-2 leading-7">We work to keep the service and practice content available, but access may occasionally be interrupted for maintenance, updates or circumstances outside our control.</p></section></div><h2 className="mt-9 text-xl font-bold">Updates</h2><p className="mt-2 leading-7 text-stone-600">We may update these terms as the platform evolves. Material changes will be posted on this page.</p></article></section>}
